package europe

import "github.com/rojack96/mcc/models"

var Austria = models.Mcc{
	Code:        232,
	Iso:         "AT",
	Country:     "Austria",
	CountryCode: 43,
	Mnc: []models.Mnc{
		{Code: "05", Network: "3"},
		{Code: "19", Network: "3"},
		{Code: "16", Network: "3"},
		{Code: "10", Network: "3"},
		{Code: "14", Network: "3"},
		{Code: "11", Network: "A1 Telekom"},
		{Code: "09", Network: "A1 Telekom"},
		{Code: "02", Network: "A1 Telekom"},
		{Code: "12", Network: "A1 Telekom"},
		{Code: "01", Network: "A1 Telekom"},
		{Code: "299", Network: "ArgoNET"},
		{Code: "299", Network: "DIALOG telekom"},
		{Code: "299", Network: "Digital Privacy"},
		{Code: "299", Network: "DIMOCO"},
		{Code: "299", Network: "educom"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "25", Network: "Holding Graz"},
		{Code: "299", Network: "Innsbrucker Kommunalbetriebe"},
		{Code: "299", Network: "kabelplus"},
		{Code: "299", Network: "Lenovo Connect"},
		{Code: "299", Network: "LINK Mobility"},
		{Code: "26", Network: "LIWEST Mobil"},
		{Code: "08", Network: "Lycamobile"},
		{Code: "17", Network: "MRS"},
		{Code: "20", Network: "Mtel"},
		{Code: "91", Network: "OBB Infrastruktur"},
		{Code: "22", Network: "Plintron"},
		{Code: "299", Network: "Simple SMS"},
		{Code: "299", Network: "Skymond Mobile"},
		{Code: "24", Network: "Smartel Services"},
		{Code: "18", Network: "smartspace"},
		{Code: "13", Network: "T-Mobile / Magenta"},
		{Code: "03", Network: "T-Mobile / Magenta"},
		{Code: "04", Network: "T-Mobile / Magenta"},
		{Code: "23", Network: "T-Mobile / Magenta"},
		{Code: "299", Network: "Telfoni"},
		{Code: "27", Network: "Tismi"},
		{Code: "07", Network: "Ventocom"},
	},
}
