package europe

import "github.com/rojack96/mcc/models"

var Danmark = models.Mcc{
	Code:        238,
	Iso:         "DK",
	Country:     "Denmark",
	CountryCode: 45,
	Mnc: []models.Mnc{
		{Code: "06", Network: "3"},
		{Code: "299", Network: "42 Telecom"},
		{Code: "299", Network: "5Tel"},
		{Code: "23", Network: "Banedanmark"},
		{Code: "299", Network: "Benemen"},
		{Code: "299", Network: "Bolignet-Aarhus"},
		{Code: "299", Network: "CBB Mobil"},
		{Code: "299", Network: "celfon"},
		{Code: "88", Network: "Cobira"},
		{Code: "299", Network: "Companymobile"},
		{Code: "13", Network: "Compatel"},
		{Code: "299", Network: "Comtalk"},
		{Code: "299", Network: "Evercall"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "299", Network: "Firmafon"},
		{Code: "299", Network: "Firstcom"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "Flexfone"},
		{Code: "17", Network: "Gotanet"},
		{Code: "42", Network: "Greenwave"},
		{Code: "299", Network: "ipnordic"},
		{Code: "299", Network: "Ipvision"},
		{Code: "299", Network: "Lancelot"},
		{Code: "299", Network: "Lebara"},
		{Code: "28", Network: "LINK Mobility"},
		{Code: "12", Network: "Lycamobile"},
		{Code: "299", Network: "Maxtel.dk"},
		{Code: "299", Network: "MI Carrier Services"},
		{Code: "299", Network: "Mitto"},
		{Code: "299", Network: "Mobiweb"},
		{Code: "14", Network: "Monty Mobile"},
		{Code: "15", Network: "Net 1"},
		{Code: "04", Network: "Nexcon.io"},
		{Code: "299", Network: "NextM2M"},
		{Code: "73", Network: "Onomondo"},
		{Code: "30", Network: "Pareteum"},
		{Code: "299", Network: "SimService"},
		{Code: "03", Network: "Syniverse"},
		{Code: "01", Network: "TDC"},
		{Code: "10", Network: "TDC"},
		{Code: "77", Network: "Telenor"},
		{Code: "02", Network: "Telenor"},
		{Code: "299", Network: "Telenor Connexion"},
		{Code: "20", Network: "Telia"},
		{Code: "96", Network: "Telia"},
		{Code: "16", Network: "Tismi"},
		{Code: "299", Network: "Tripple Track"},
		{Code: "299", Network: "Uni-tel"},
		{Code: "25", Network: "Viahub"},
		{Code: "299", Network: "Viptel"},
		{Code: "08", Network: "Voxbone / Bandwidth"},
	},
}
