package europe

import "github.com/rojack96/mcc/models"

var Italy = models.Mcc{
	Code:        222,
	Iso:         "IT",
	Country:     "Italy",
	CountryCode: 39,
	Mnc: []models.Mnc{
		{Code: "299", Network: "1Mobile"},
		{Code: "299", Network: "A-Tono"},
		{Code: "40", Network: "Agile Telecom"},
		{Code: "34", Network: "BT mobile"},
		{Code: "299", Network: "Esendex"},
		{Code: "299", Network: "Compatel"},
		{Code: "53", Network: "CoopVoce"},
		{Code: "299", Network: "Daily Telecom Mobile"},
		{Code: "36", Network: "Digi"},
		{Code: "299", Network: "DireQ"},
		{Code: "42", Network: "Enel"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "8", Network: "Fastweb"},
		{Code: "999", Network: "Fix Line"},
		{Code: "99", Network: "WindTre / Hi3G"},
		{Code: "50", Network: "Iliad"},
		{Code: "299", Network: "Kaleyra"},
		{Code: "39", Network: "SMS.it / LINK Mobility"},
		{Code: "35", Network: "Lycamobile"},
		{Code: "7", Network: "Noverca Italia"},
		{Code: "54", Network: "Plintron"},
		{Code: "33", Network: "Poste Mobile"},
		{Code: "999", Network: "Premium Numbers"},
		{Code: "58", Network: "rdcom"},
		{Code: "30", Network: "RFI"},
		{Code: "56", Network: "spusu"},
		{Code: "1", Network: "TIM"},
		{Code: "48", Network: "Telecom Italia Mobile"},
		{Code: "43", Network: "Telecom Italia Mobile"},
		{Code: "299", Network: "Sparkle"},
		{Code: "299", Network: "Tiscali"},
		{Code: "44", Network: "Mundio"},
		{Code: "51", Network: "ho."},
		{Code: "49", Network: "Vianova Mobile"},
		{Code: "10", Network: "Vodafone"},
		{Code: "6", Network: "Vodafone"},
		{Code: "299", Network: "Vola"},
		{Code: "299", Network: "Webcom"},
		{Code: "88", Network: "WindTre / WIND"},
		{Code: "37", Network: "WindTre / Hi3G"},
	},
}
