package europe

import "github.com/rojack96/mcc/models"

var Netherlands = models.Mcc{
	Code:        204,
	Iso:         "NL",
	Country:     "Netherlands",
	CountryCode: 31,
	Mnc: []models.Mnc{
		{Code: "299", Network: "88 mobile"},
		{Code: "299", Network: "AGMS"},
		{Code: "30", Network: "ASPIDER Solutions"},
		{Code: "299", Network: "Belcentrale"},
		{Code: "299", Network: "BodyTrace"},
		{Code: "299", Network: "Combird Mobile"},
		{Code: "299", Network: "Dean Mobile"},
		{Code: "299", Network: "Eazit"},
		{Code: "5", Network: "ElephantTalk"},
		{Code: "299", Network: "EziMobile"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "interactive digital media / IDM"},
		{Code: "0", Network: "Intovoice"},
		{Code: "299", Network: "KeenMobile"},
		{Code: "23", Network: "KORE"},
		{Code: "10", Network: "KPN"},
		{Code: "69", Network: "KPN"},
		{Code: "12", Network: "KPN"},
		{Code: "8", Network: "KPN"},
		{Code: "27", Network: "L-mobi"},
		{Code: "28", Network: "Lancelot"},
		{Code: "98", Network: "Lancelot"},
		{Code: "9", Network: "Lycamobile"},
		{Code: "63", Network: "MessageBird"},
		{Code: "299", Network: "mGage"},
		{Code: "299", Network: "Motto"},
		{Code: "7", Network: "Move / Teleena"},
		{Code: "299", Network: "Okta8"},
		{Code: "299", Network: "Premium Numbers"},
		{Code: "299", Network: "Premium Routing"},
		{Code: "24", Network: "Private Mobility"},
		{Code: "21", Network: "ProRail"},
		{Code: "299", Network: "Redworks"},
		{Code: "26", Network: "SpeakUp"},
		{Code: "2", Network: "T-Mobile"},
		{Code: "20", Network: "T-Mobile"},
		{Code: "16", Network: "T-Mobile"},
		{Code: "29", Network: "Tismi"},
		{Code: "33", Network: "Truphone"},
		{Code: "6", Network: "Vectone Mobile"},
		{Code: "4", Network: "Vodafone"},
		{Code: "3", Network: "Voiceworks Mobile"},
		{Code: "15", Network: "Ziggo"},
		{Code: "18", Network: "Ziggo Services"},
	},
}
