package europe

import "github.com/rojack96/mcc/models"

var Russia = models.Mcc{
	Code:        250,
	Iso:         "RU",
	Country:     "Russia",
	CountryCode: 79,
	Mnc: []models.Mnc{
		{Code: "299", Network: "Antares"},
		{Code: "299", Network: "Arktur"},
		{Code: "299", Network: "Astran"},
		{Code: "299", Network: "ASVT"},
		{Code: "299", Network: "Aurora Telecom"},
		{Code: "99", Network: "Beeline"},
		{Code: "299", Network: "Beliton"},
		{Code: "299", Network: "BIT-CENTR"},
		{Code: "299", Network: "Center 2M"},
		{Code: "299", Network: "Cifra 1"},
		{Code: "299", Network: "CountryCom"},
		{Code: "299", Network: "ECO Networks"},
		{Code: "299", Network: "Elemte"},
		{Code: "299", Network: "ER-Telecom"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "Gazprom Telecom"},
		{Code: "48", Network: "Global Telecom"},
		{Code: "55", Network: "Glonass"},
		{Code: "299", Network: "GLONASS MOBILE"},
		{Code: "299", Network: "Integral"},
		{Code: "299", Network: "Internod"},
		{Code: "299", Network: "Intersvyaz-2"},
		{Code: "34", Network: "Krymtelecom"},
		{Code: "299", Network: "KvatroPlus"},
		{Code: "299", Network: "Lardex"},
		{Code: "54", Network: "Letai Mobile"},
		{Code: "299", Network: "Lycamobile"},
		{Code: "57", Network: "Matrix Mobile"},
		{Code: "299", Network: "Media-Market"},
		{Code: "02", Network: "Megafon"},
		{Code: "299", Network: "Metro-Pei"},
		{Code: "299", Network: "MGTS"},
		{Code: "299", Network: "Miatel"},
		{Code: "299", Network: "MOSTELECOM"},
		{Code: "35", Network: "Motiv"},
		{Code: "299", Network: "MSN Telekom"},
		{Code: "01", Network: "MTS"},
		{Code: "42", Network: "MTT"},
		{Code: "299", Network: "NCI"},
		{Code: "299", Network: "NETBYNET"},
		{Code: "299", Network: "New Mobile Communications"},
		{Code: "299", Network: "OBIT"},
		{Code: "299", Network: "Orange Business Services"},
		{Code: "299", Network: "PIN"},
		{Code: "299", Network: "Plintron"},
		{Code: "299", Network: "Quantech"},
		{Code: "299", Network: "RECONN"},
		{Code: "299", Network: "Reteyl Innovatsii"},
		{Code: "299", Network: "Sberbank-Telecom"},
		{Code: "33", Network: "SEVTELECOM"},
		{Code: "299", Network: "Sim Sim"},
		{Code: "299", Network: "Sintonik"},
		{Code: "299", Network: "Sky Networks"},
		{Code: "09", Network: "Skylink"},
		{Code: "299", Network: "SkyNet"},
		{Code: "299", Network: "Sonet"},
		{Code: "299", Network: "Sprint"},
		{Code: "299", Network: "Start"},
		{Code: "299", Network: "SunSIM"},
		{Code: "299", Network: "Surgutneftegaz"},
		{Code: "299", Network: "Svyazresurs-Mobile"},
		{Code: "299", Network: "Tander"},
		{Code: "20", Network: "Tele2"},
		{Code: "12", Network: "Tele2"},
		{Code: "299", Network: "Tinkoff Mobile"},
		{Code: "299", Network: "TMT"},
		{Code: "299", Network: "TransMobilCom"},
		{Code: "299", Network: "TRASTEL"},
		{Code: "299", Network: "TRN-telecom"},
		{Code: "299", Network: "TTK"},
		{Code: "299", Network: "TTK-Svyaz"},
		{Code: "299", Network: "TVE"},
		{Code: "299", Network: "UnitTelecom"},
		{Code: "299", Network: "Unycel"},
		{Code: "299", Network: "Vainah Telecom"},
		{Code: "299", Network: "ViKom"},
		{Code: "299", Network: "Virgin Connect"},
		{Code: "299", Network: "Voentelecom"},
		{Code: "77", Network: "Glonass"},
		{Code: "60", Network: "Volna Mobile"},
		{Code: "299", Network: "VTB Mobile"},
		{Code: "32", Network: "Win Mobile"},
		{Code: "11", Network: "Yota"},
	},
}
