package europe

import "github.com/rojack96/mcc/models"

var Spain = models.Mcc{
	Code:        214,
	Iso:         "ES",
	Country:     "Spain",
	CountryCode: 34,
	Mnc: []models.Mnc{
		{Code: "299", Network: "ACN"},
		{Code: "299", Network: "Adamo Telecom"},
		{Code: "36", Network: "Alai"},
		{Code: "2", Network: "Alta Tecnologia en Comunicacions"},
		{Code: "299", Network: "Aurea"},
		{Code: "14", Network: "Avatel Movil"},
		{Code: "299", Network: "Billing Financial"},
		{Code: "299", Network: "Bluephone"},
		{Code: "299", Network: "CloudComms"},
		{Code: "299", Network: "Dialoga"},
		{Code: "22", Network: "Digi.Mobil"},
		{Code: "299", Network: "Dragonet"},
		{Code: "8", Network: "Euskaltel Movil"},
		{Code: "299", Network: "Evolutio"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "Global"},
		{Code: "299", Network: "GNET"},
		{Code: "34", Network: "ION MOBILE"},
		{Code: "299", Network: "Jetnet"},
		{Code: "299", Network: "Lemonvil"},
		{Code: "25", Network: "Lycamobile"},
		{Code: "17", Network: "mobil R"},
		{Code: "38", Network: "Movistar"},
		{Code: "7", Network: "Movistar"},
		{Code: "5", Network: "Movistar"},
		{Code: "299", Network: "Olephone"},
		{Code: "299", Network: "On Movil"},
		{Code: "299", Network: "Oniti Telecom"},
		{Code: "299", Network: "OperadorsCat"},
		{Code: "9", Network: "Orange"},
		{Code: "21", Network: "Orange"},
		{Code: "3", Network: "Orange"},
		{Code: "299", Network: "Pepephone"},
		{Code: "299", Network: "Premium Numbers"},
		{Code: "299", Network: "PTV Telecom movil"},
		{Code: "299", Network: "Quattre"},
		{Code: "299", Network: "Sarenet"},
		{Code: "299", Network: "SEWAN"},
		{Code: "19", Network: "Simyo"},
		{Code: "35", Network: "SUMA movil"},
		{Code: "299", Network: "Suop"},
		{Code: "299", Network: "Syma"},
		{Code: "16", Network: "mobil R"},
		{Code: "299", Network: "Telsome"},
		{Code: "299", Network: "The Telecom Boutique"},
		{Code: "27", Network: "Truphone"},
		{Code: "12", Network: "Venus Movil"},
		{Code: "1", Network: "Vodafone"},
		{Code: "37", Network: "Vodafone"},
		{Code: "6", Network: "Vodafone"},
		{Code: "299", Network: "Vodafone Enabler"},
		{Code: "33", Network: "Yoigo"},
		{Code: "23", Network: "Yoigo"},
		{Code: "29", Network: "Yoigo"},
		{Code: "4", Network: "Yoigo"},
		{Code: "299", Network: "You Mobile"},
		{Code: "10", Network: "Zinnia"},
	},
}
