package europe

import "github.com/rojack96/mcc/models"

var Sweden = models.Mcc{
	Code:        240,
	Iso:         "SE",
	Country:     "Sweden",
	CountryCode: 46,
	Mnc: []models.Mnc{
		{Code: "16"},
		{Code: "35", Network: "42 Telecom"},
		{Code: "13", Network: "A3"},
		{Code: "299", Network: "Advoco"},
		{Code: "299"},
		{Code: "299", Network: "Allo Telecom"},
		{Code: "299", Network: "Bahnhof"},
		{Code: "299", Network: "Benemen"},
		{Code: "299", Network: "Biztel"},
		{Code: "299", Network: "BM Sverige"},
		{Code: "299", Network: "Bredband 2"},
		{Code: "299", Network: "Bredbandsson"},
		{Code: "299", Network: "BSG"},
		{Code: "299", Network: "Chilimobil"},
		{Code: "11", Network: "Com Hem"},
		{Code: "09", Network: "Com4"},
		{Code: "32", Network: "Compatel"},
		{Code: "299", Network: "Connectel"},
		{Code: "299", Network: "Core Telecom"},
		{Code: "299", Network: "easy pbx"},
		{Code: "299", Network: "EasyTelecom"},
		{Code: "22", Network: "EUtel"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "299", Network: "Fastcom"},
		{Code: "299", Network: "Febo Telecom"},
		{Code: "299", Network: "Fello"},
		{Code: "299", Network: "Fibio"},
		{Code: "63", Network: "Fink Telecom"},
		{Code: "299", Network: "Firstcom"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "Fonia"},
		{Code: "18", Network: "Messit / Minicall"},
		{Code: "299", Network: "Global Telefoni"},
		{Code: "299", Network: "GlobalConnect"},
		{Code: "27", Network: "Globetouch"},
		{Code: "17", Network: "Gotanet"},
		{Code: "02", Network: "3"},
		{Code: "299", Network: "Horisen"},
		{Code: "299", Network: "iCentrex"},
		{Code: "23", Network: "Infobip"},
		{Code: "299", Network: "InfraCom"},
		{Code: "36", Network: "interactive digital media / IDM"},
		{Code: "299", Network: "Ipify"},
		{Code: "299", Network: "Junyverse"},
		{Code: "299", Network: "Karma Mobil"},
		{Code: "299", Network: "Lancelot"},
		{Code: "28", Network: "LINK Mobility"},
		{Code: "299", Network: "Loxysoft"},
		{Code: "12", Network: "Lycamobile"},
		{Code: "299", Network: "Maingate"},
		{Code: "299", Network: "Megaphone"},
		{Code: "299", Network: "MessageBird"},
		{Code: "29", Network: "MI Carrier Services"},
		{Code: "299", Network: "miniTel"},
		{Code: "299", Network: "Mitto"},
		{Code: "33", Network: "Mobile Arts"},
		{Code: "43", Network: "MobiWeb"},
		{Code: "25", Network: "Monty Mobile"},
		{Code: "40", Network: "Netmore"},
		{Code: "39", Network: "Primlight"},
		{Code: "31", Network: "Rebtel"},
		{Code: "20", Network: "Sierra Wireless"},
		{Code: "37", Network: "Sinch"},
		{Code: "31"},
		{Code: "45", Network: "Spirius"},
		{Code: "07", Network: "Tele2"},
		{Code: "14", Network: "Tele2"},
		{Code: "05", Network: "Tele2"},
		{Code: "44", Network: "Telenabler"},
		{Code: "42", Network: "Telenor Connexion"},
		{Code: "04", Network: "Telenor"},
		{Code: "08", Network: "Telenor"},
		{Code: "01", Network: "Telia"},
		{Code: "299", Network: "Tell it to Mi"},
		{Code: "299", Network: "Telness"},
		{Code: "03", Network: "Net 1"},
		{Code: "48", Network: "Tismi"},
		{Code: "299", Network: "Tolv Mobil"},
		{Code: "21", Network: "Trafikverket"},
		{Code: "26", Network: "Twilio"},
		{Code: "299", Network: "Unicorn Telecom"},
		{Code: "19", Network: "Vectone Mobile"},
		{Code: "299", Network: "Verbal"},
		{Code: "46", Network: "Viahub"},
		{Code: "47", Network: "Viatel"},
		{Code: "299", Network: "Vobbiz"},
		{Code: "299", Network: "Voice Integrate"},
		{Code: "299", Network: "Voicetech"},
		{Code: "38", Network: "Voxbone / Bandwidth"},
		{Code: "299", Network: "Weelia"},
		{Code: "299", Network: "Wifi.se"},
		{Code: "299", Network: "Wifog Sverige"},
		{Code: "299", Network: "XPLORA"},
	},
}
