package nations

import "github.com/rojack96/mcc/models"

var Austria = models.Mcc{
	Code:        232,
	Iso:         "AT",
	Country:     "Austria",
	CountryCode: 43,
	Mnc: []models.Mnc{
		{"05", "3"},
		{"19", "3"},
		{"16", "3"},
		{"10", "3"},
		{"14", "3"},
		{"11", "A1 Telekom"},
		{"09", "A1 Telekom"},
		{"02", "A1 Telekom"},
		{"12", "A1 Telekom"},
		{"01", "A1 Telekom"},
		{"299", "ArgoNET"},
		{"299", "DIALOG telekom"},
		{"299", "Digital Privacy"},
		{"299", "DIMOCO"},
		{"299", "educom"},
		{"299", "Failed Calls"},
		{"999", "Fix Line"},
		{"25", "Holding Graz"},
		{"299", "Innsbrucker Kommunalbetriebe"},
		{"299", "kabelplus"},
		{"299", "Lenovo Connect"},
		{"299", "LINK Mobility"},
		{"26", "LIWEST Mobil"},
		{"08", "Lycamobile"},
		{"17", "MRS"},
		{"20", "Mtel"},
		{"91", "OBB Infrastruktur"},
		{"22", "Plintron"},
		{"299", "Simple SMS"},
		{"299", "Skymond Mobile"},
		{"24", "Smartel Services"},
		{"18", "smartspace"},
		{"13", "T-Mobile / Magenta"},
		{"03", "T-Mobile / Magenta"},
		{"04", "T-Mobile / Magenta"},
		{"23", "T-Mobile / Magenta"},
		{"299", "Telfoni"},
		{"27", "Tismi"},
		{"07", "Ventocom"},
	},
}
