package nations

import "github.com/rojack96/mcc/models"

var Italy = models.Mcc{
	Code:        222,
	Iso:         "IT",
	Country:     "Italy",
	CountryCode: 39,
	Mnc: []models.Mnc{
		{"299", "1Mobile"},
		{"299", "A-Tono"},
		{"40", "Agile Telecom"},
		{"34", "BT mobile"},
		{"299", "Esendex"},
		{"299", "Compatel"},
		{"53", "CoopVoce"},
		{"299", "Daily Telecom Mobile"},
		{"36", "Digi"},
		{"299", "DireQ"},
		{"42", "Enel"},
		{"299", "Failed Calls"},
		{"8", "Fastweb"},
		{"999", "Fix Line"},
		{"99", "WindTre / Hi3G"},
		{"50", "Iliad"},
		{"299", "Kaleyra"},
		{"39", "SMS.it / LINK Mobility"},
		{"35", "Lycamobile"},
		{"7", "Noverca Italia"},
		{"54", "Plintron"},
		{"33", "Poste Mobile"},
		{"999", "Premium Numbers"},
		{"58", "rdcom"},
		{"30", "RFI"},
		{"56", "spusu"},
		{"1", "TIM"},
		{"48", "Telecom Italia Mobile"},
		{"43", "Telecom Italia Mobile"},
		{"299", "Sparkle"},
		{"299", "Tiscali"},
		{"44", "Mundio"},
		{"51", "ho."},
		{"49", "Vianova Mobile"},
		{"10", "Vodafone"},
		{"6", "Vodafone"},
		{"299", "Vola"},
		{"299", "Webcom"},
		{"88", "WindTre / WIND"},
		{"37", "WindTre / Hi3G"},
	},
}
