package nations

import "github.com/rojack96/mcc/models"

var Spain = models.Mcc{
	Code:        214,
	Iso:         "ES",
	Country:     "Spain",
	CountryCode: 34,
	Mnc: []models.Mnc{
		{"299", "ACN"},
		{"299", "Adamo Telecom"},
		{"36", "Alai"},
		{"2", "Alta Tecnologia en Comunicacions"},
		{"299", "Aurea"},
		{"14", "Avatel Movil"},
		{"299", "Billing Financial"},
		{"299", "Bluephone"},
		{"299", "CloudComms"},
		{"299", "Dialoga"},
		{"22", "Digi.Mobil"},
		{"299", "Dragonet"},
		{"8", "Euskaltel Movil"},
		{"299", "Evolutio"},
		{"299", "Failed Calls"},
		{"999", "Fix Line"},
		{"299", "Global"},
		{"299", "GNET"},
		{"34", "ION MOBILE"},
		{"299", "Jetnet"},
		{"299", "Lemonvil"},
		{"25", "Lycamobile"},
		{"17", "mobil R"},
		{"38", "Movistar"},
		{"7", "Movistar"},
		{"5", "Movistar"},
		{"299", "Olephone"},
		{"299", "On Movil"},
		{"299", "Oniti Telecom"},
		{"299", "OperadorsCat"},
		{"9", "Orange"},
		{"21", "Orange"},
		{"3", "Orange"},
		{"299", "Pepephone"},
		{"299", "Premium Numbers"},
		{"299", "PTV Telecom movil"},
		{"299", "Quattre"},
		{"299", "Sarenet"},
		{"299", "SEWAN"},
		{"19", "Simyo"},
		{"35", "SUMA movil"},
		{"299", "Suop"},
		{"299", "Syma"},
		{"16", "mobil R"},
		{"299", "Telsome"},
		{"299", "The Telecom Boutique"},
		{"27", "Truphone"},
		{"12", "Venus Movil"},
		{"1", "Vodafone"},
		{"37", "Vodafone"},
		{"6", "Vodafone"},
		{"299", "Vodafone Enabler"},
		{"33", "Yoigo"},
		{"23", "Yoigo"},
		{"29", "Yoigo"},
		{"4", "Yoigo"},
		{"299", "You Mobile"},
		{"10", "Zinnia"},
	},
}
