package nations

import "github.com/rojack96/mcc/models"

var UnitedKingdom = models.Mcc{
	Code:        234,
	Iso:         "GB",
	Country:     "United Kingdom",
	CountryCode: 44,
	Mnc: []models.Mnc{
		{"78", "Airwave"},
		{"29", "aql"},
		{"76", "BT Group"},
		{"00", "BT Group"},
		{"08", "BT OnePhone"},
		{"18", "Cloud9"},
		{"30", "EE/Everything Everywhere"},
		{"32", "EE/Everything Everywhere"},
		{"33", "EE/Everything Everywhere"},
		{"31", "EE/Everything Everywhere"},
		{"299", "Failed Calls"},
		{"999", "Fix Line"},
		{"17", "FlexTel"},
		{"04", "FMS Solutions"},
		{"39", "Gamma Mobile"},
		{"24", "Greenfone"},
		{"72", "Hanhaa Mobile"},
		{"71", "Home Office"},
		{"20", "3"},
		{"94", "3"},
		{"23", "Icron Network"},
		{"03", "Jersey Airtel"},
		{"35", "JSC Ingenicum"},
		{"50", "JT Mobile"},
		{"14", "LINK Mobility"},
		{"26", "Lycamobile"},
		{"58", "Manx Telecom Mobile"},
		{"28", "Marathon Telecom"},
		{"75", "Mass Response Service GmbH"},
		{"56", "NCSC"},
		{"95", "Network Rail"},
		{"12", "Network Rail"},
		{"13", "Network Rail"},
		{"51", "now broadband"},
		{"34", "Orange"},
		{"74", "Pareteum"},
		{"57", "Sky"},
		{"40", "spusu"},
		{"55", "Sure Guernsey"},
		{"36", "Sure Isle of Man"},
		{"99", "Sure Jersey"},
		{"37", "Synectiv"},
		{"16", "Talk Talk"},
		{"27", "Tata Communications Ltd"},
		{"11", "O2"},
		{"10", "O2"},
		{"02", "O2"},
		{"22", "Telesign Mobile"},
		{"19", "TeleWare"},
		{"09", "Tismi"},
		{"25", "Truphone"},
		{"01", "Vectone Mobile"},
		{"38", "Virgin Mobile"},
		{"91", "Vodafone"},
		{"07", "Vodafone"},
		{"15", "Vodafone"},
		{"92", "Vodafone"},
		{"77", "Vodafone"},
		{"89", "Vodafone"},
	},
}
