package countries

import "github.com/rojack96/mcc/models"

var Finland = models.Mcc{
	Code:        244,
	Iso:         "FI",
	Country:     "Finland",
	CountryCode: 358,
	Mnc: []models.Mnc{
		{Code: "14", Network: "Alcom"},
		{Code: "299", Network: "Benemen"},
		{Code: "26", Network: "Compatel"},
		{Code: "299", Network: "Cuuma"},
		{Code: "13", Network: "DNA"},
		{Code: "12", Network: "DNA"},
		{Code: "03", Network: "DNA"},
		{Code: "04", Network: "DNA"},
		{Code: "06", Network: "Elisa"},
		{Code: "21", Network: "Elisa"},
		{Code: "05", Network: "Elisa"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "interactive digital media / IDM"},
		{Code: "299", Network: "IPIFY"},
		{Code: "299", Network: "Lancelot"},
		{Code: "299", Network: "MI Carrier Services"},
		{Code: "299", Network: "MobiWeb"},
		{Code: "24", Network: "Nord Connect"},
		{Code: "39", Network: "NSN"},
		{Code: "41", Network: "NSN"},
		{Code: "40", Network: "NSN"},
		{Code: "07", Network: "NSN"},
		{Code: "38", Network: "NSN"},
		{Code: "08", Network: "NSN"},
		{Code: "09", Network: "NSN"},
		{Code: "299", Network: "Premium Numbers"},
		{Code: "299", Network: "RAILI"},
		{Code: "43", Network: "Telavox"},
		{Code: "36", Network: "Telia"},
		{Code: "91", Network: "Telia"},
		{Code: "15", Network: "Telit"},
		{Code: "37", Network: "Tismi"},
		{Code: "299", Network: "TravelSim"},
		{Code: "299", Network: "Twilio"},
		{Code: "35", Network: "Ukko Mobile"},
		{Code: "42", Network: "Viahub"},
		{Code: "47", Network: "VIRVE"},
		{Code: "46", Network: "VIRVE"},
		{Code: "33", Network: "VIRVE"},
		{Code: "45", Network: "VIRVE"},
		{Code: "32", Network: "Voxbone / Bandwidth"},
	},
}
