package countries

import "github.com/rojack96/mcc/models"

var France = models.Mcc{
	Code:        208,
	Iso:         "FR",
	Country:     "France",
	CountryCode: 33,
	Mnc: []models.Mnc{
		{Code: "299", Network: "Add-On Multimedia"},
		{Code: "299", Network: "Afone Mobile"},
		{Code: "28", Network: "Airmob"},
		{Code: "299", Network: "Alphalink"},
		{Code: "299", Network: "Annatel"},
		{Code: "299", Network: "Atlas"},
		{Code: "299", Network: "Auchan"},
		{Code: "299", Network: "Axialys"},
		{Code: "299", Network: "Bazile"},
		{Code: "299", Network: "BJT"},
		{Code: "88", Network: "Bouygues Telecom"},
		{Code: "21", Network: "Bouygues Telecom"},
		{Code: "20", Network: "Bouygues Telecom"},
		{Code: "299", Network: "Bretagne Telecom"},
		{Code: "299", Network: "CAT"},
		{Code: "299", Network: "CELESTE"},
		{Code: "34", Network: "Cellhire"},
		{Code: "299", Network: "Codepi"},
		{Code: "299", Network: "Coolwave"},
		{Code: "27", Network: "Coriolis"},
		{Code: "299", Network: "CPRO"},
		{Code: "299", Network: "CRH"},
		{Code: "299", Network: "CRT"},
		{Code: "299", Network: "CTExcel"},
		{Code: "299", Network: "Doctolib"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "Foliateam"},
		{Code: "15", Network: "Free Mobile"},
		{Code: "35", Network: "Free Mobile"},
		{Code: "36", Network: "Free Mobile"},
		{Code: "16", Network: "Free Mobile"},
		{Code: "94", Network: "Halys"},
		{Code: "299", Network: "Happy Telecom"},
		{Code: "299", Network: "Hexatel"},
		{Code: "89", Network: "Hub One"},
		{Code: "299", Network: "i-via"},
		{Code: "37", Network: "IP Directions"},
		{Code: "299", Network: "IP Telecom"},
		{Code: "299", Network: "Iptis"},
		{Code: "299", Network: "JOi"},
		{Code: "299", Network: "Kertel"},
		{Code: "299", Network: "Keyyo Mobile"},
		{Code: "299", Network: "La Poste Mobile"},
		{Code: "299", Network: "LASOTEL"},
		{Code: "38", Network: "Lebara"},
		{Code: "17", Network: "Legos"},
		{Code: "299", Network: "Linkt"},
		{Code: "299", Network: "LITEYEAR"},
		{Code: "25", Network: "Lycamobile"},
		{Code: "24", Network: "MobiquiThings"},
		{Code: "3", Network: "MobiquiThings"},
		{Code: "299", Network: "Netcom"},
		{Code: "39", Network: "Networth Telecom"},
		{Code: "299", Network: "Nordnet"},
		{Code: "26", Network: "NRJ"},
		{Code: "299", Network: "onoff"},
		{Code: "299", Network: "OpenIP"},
		{Code: "1", Network: "Orange"},
		{Code: "91", Network: "Orange"},
		{Code: "2", Network: "Orange"},
		{Code: "32", Network: "Orange"},
		{Code: "299", Network: "Paritel"},
		{Code: "299", Network: "Prixtel"},
		{Code: "299", Network: "SCT TELECOM"},
		{Code: "299", Network: "Sewan Communications"},
		{Code: "13", Network: "SFR"},
		{Code: "8", Network: "SFR"},
		{Code: "11", Network: "SFR"},
		{Code: "10", Network: "SFR"},
		{Code: "9", Network: "SFR"},
		{Code: "299", Network: "SIMbioz"},
		{Code: "30", Network: "Syma Mobile"},
		{Code: "299", Network: "TDF"},
		{Code: "299", Network: "Tismi"},
		{Code: "22", Network: "Transatel"},
		{Code: "299", Network: "Trunkline"},
		{Code: "12", Network: "Truphone"},
		{Code: "299", Network: "unyc"},
		{Code: "299", Network: "VA SOLUTIONS"},
		{Code: "31", Network: "Vectone Mobile"},
		{Code: "299", Network: "VOIP Telecom"},
	},
}
