package countries

import "github.com/rojack96/mcc/models"

var Germany = models.Mcc{
	Code:        262,
	Iso:         "DE",
	Country:     "Germany",
	CountryCode: 49,
	Mnc: []models.Mnc{
		{Code: "23", Network: "1&1"},
		{Code: "299", Network: "Argon Networks"},
		{Code: "10", Network: "DB Netz"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "14", Network: "Lebara"},
		{Code: "43", Network: "Lycamobile"},
		{Code: "13", Network: "T-mobile"},
		{Code: "25", Network: "Mtel"},
		{Code: "21", Network: "Multiconnect"},
		{Code: "12", Network: "sipgate"},
		{Code: "22", Network: "sipgate"},
		{Code: "01", Network: "T-mobile"},
		{Code: "78", Network: "T-mobile"},
		{Code: "06", Network: "T-mobile"},
		{Code: "24", Network: "TelcoVillage"},
		{Code: "05", Network: "Telefonica / O2"},
		{Code: "20", Network: "Telefonica / O2"},
		{Code: "17", Network: "Telefonica / O2"},
		{Code: "03", Network: "Telefonica / O2"},
		{Code: "16", Network: "Telefonica / O2"},
		{Code: "11", Network: "Telefonica / O2"},
		{Code: "08", Network: "Telefonica / O2"},
		{Code: "07", Network: "Telefonica / O2"},
		{Code: "299", Network: "Tismi"},
		{Code: "42", Network: "Truphone"},
		{Code: "02", Network: "Vodafone"},
		{Code: "09", Network: "Vodafone"},
		{Code: "04", Network: "Vodafone"},
	},
}
