package countries

import "github.com/rojack96/mcc/models"

var GuamAndUnitedStates310 = models.Mcc{
	Code:        310,
	Iso:         "GU/US",
	Country:     "Guam and United States",
	CountryCode: 0,
	Mnc: []models.Mnc{
		{Code: "012", Network: "Cellco Partnership"},
		{Code: "016", Network: "Leap Wireless International Inc."},
		{Code: "020", Network: "Union Telephone Co."},
		{Code: "030", Network: "Centennial Communications Corp."},
		{Code: "032", Network: "IT&E OverSeas"},
		{Code: "033", Network: "Guam Teleph. Auth."},
		{Code: "040", Network: "Matanuska Tel. Assn. Inc."},
		{Code: "050", Network: "ACS Wireless Inc."},
		{Code: "070", Network: "AT&T Wireless Inc."},
		{Code: "080", Network: "Corr Wireless Communications LLC"},
		{Code: "090", Network: "Edge Wireless LLC"},
		{Code: "100", Network: "Plateau Telecommunications Inc."},
		{Code: "130", Network: "North Carolina RSA 3 Cellular Tel. Co."},
		{Code: "140", Network: "GTA Wireless"},
		{Code: "150", Network: "AT&T Wireless Inc."},
		{Code: "160", Network: "T-Mobile"},
		{Code: "170", Network: "AT&T Wireless Inc."},
		{Code: "200", Network: "T-Mobile"},
		{Code: "210", Network: "T-Mobile"},
		{Code: "220", Network: "T-Mobile"},
		{Code: "230", Network: "T-Mobile"},
		{Code: "240", Network: "T-Mobile"},
		{Code: "250", Network: "T-Mobile"},
		{Code: "26", Network: "Cook Telecom Inc."},
		{Code: "260", Network: "T-Mobile"},
		{Code: "270", Network: "T-Mobile"},
		{Code: "290", Network: "NEP Cellcorp Inc."},
		{Code: "300", Network: "T-Mobile USA"},
		{Code: "310", Network: "T-Mobile USA"},
		{Code: "320", Network: "Smith Bagley Inc."},
		{Code: "330", Network: "T-Mobile USA"},
		{Code: "34", Network: "Nevada Wireless LLC"},
		{Code: "340", Network: "Westlink Communications, LLC"},
		{Code: "350", Network: "Mohave Cellular LP"},
		{Code: "360", Network: "Cellular Network Partnership LLC"},
		{Code: "370", Network: "Docomo"},
		{Code: "38", Network: "USA 3650 AT&T"},
		{Code: "380", Network: "AT&T Wireless Inc."},
		{Code: "390", Network: "Yorkville Telephone Cooperative"},
		{Code: "400", Network: "Minnesota Southern Wireless Company dba Hickory Tech"},
		{Code: "410", Network: "AT&T Wireless Inc."},
		{Code: "420", Network: "Cincinnati Bell Wireless LLC"},
		{Code: "430", Network: "GCI Communication Corp."},
		{Code: "440", Network: "Dobson Cellular Systems"},
		{Code: "450", Network: "Northeast Colorado Cellular Inc."},
		{Code: "46", Network: "SIMMETRY"},
		{Code: "460", Network: "TMP Corporation"},
		{Code: "470", Network: "Docomo"},
		{Code: "480", Network: "Choice Phone LLC"},
		{Code: "490", Network: "Triton PCS"},
		{Code: "500", Network: "Public Service Cellular Inc."},
		{Code: "510", Network: "Airtel Wireless LLC"},
		{Code: "520", Network: "VeriSign"},
		{Code: "530", Network: "West Virginia Wireless"},
		{Code: "540", Network: "Oklahoma Western Telephone Co."},
		{Code: "560", Network: "AT&T Wireless Inc."},
		{Code: "570", Network: "MTPCS LLC"},
		{Code: "580", Network: "PCS ONE"},
		{Code: "590", Network: "Cellco Partnership"},
		{Code: "60", Network: "Consolidated Telcom"},
		{Code: "600", Network: "New-Cell Inc."},
		{Code: "610", Network: "Elkhart Telephone Co. Inc. dba Epic Touch Co."},
		{Code: "620", Network: "Coleman County Telecommunications Inc. (Trans Texas"},
		{Code: "630", Network: "Choice Wireless LC"},
		{Code: "640", Network: "Airadigm Communications Inc."},
		{Code: "650", Network: "Jasper"},
		{Code: "660", Network: "T-Mobile"},
		{Code: "670", Network: "Northstar"},
		{Code: "680", Network: "AT&T Wireless Inc."},
		{Code: "690", Network: "Keystone Wireless LLC"},
		{Code: "700", Network: "Cross Valliant Cellular Partnership"},
		{Code: "710", Network: "Arctic Slope Telephone Association Cooperative Inc."},
		{Code: "730", Network: "United States Cellular Corp."},
		{Code: "740", Network: "Telemetrix Inc."},
		{Code: "750", Network: "East Kentucky Network LLC"},
		{Code: "760", Network: "Panhandle Telephone Cooperative Inc."},
		{Code: "770", Network: "Iowa Wireless Services LLC"},
		{Code: "780", Network: "Message Express Company dba Airlink PCS"},
		{Code: "790", Network: "Pinpoint Wireless Inc."},
		{Code: "800", Network: "T-Mobile USA"},
		{Code: "830", Network: "Caprock Cellular Ltd. Partnership"},
		{Code: "850", Network: "Aeris Communications Inc."},
		{Code: "860", Network: "Texas RSA 15B2 Limited Partnership"},
		{Code: "870", Network: "Kaplan Telephone Company Inc."},
		{Code: "880", Network: "Advantage Cellular Systems Inc."},
		{Code: "890", Network: "Cellco Partnership"},
		{Code: "900", Network: "Cable & Communications Corp."},
		{Code: "920", Network: "Get Mobile Inc."},
		{Code: "930", Network: "Copper Valley Wireless Inc."},
		{Code: "940", Network: "Poka Lambro Telecommunications Ltd."},
		{Code: "960", Network: "Uintah Basin Electronics Telecommunications Inc."},
		{Code: "970", Network: "Globalstar USA LLC"},
		{Code: "980", Network: "AT&T Wireless Services Inc."},
	},
}
