package countries

import "github.com/rojack96/mcc/models"

var GuamAndUnitedStates311 = models.Mcc{
	Code:        311,
	Iso:         "GU/US",
	Country:     "Guam and United States",
	CountryCode: 0,
	Mnc: []models.Mnc{
		{Code: "000", Network: "Mid-Tex Cellular Ltd"},
		{Code: "010", Network: "Missouri RSA No 5 Partnership"},
		{Code: "030", Network: "Indigo Wireless Inc."},
		{Code: "040", Network: "Commnet of Arizona LLC"},
		{Code: "050", Network: "Thumb Cellular Limited Partnership"},
		{Code: "070", Network: "Wisconsin RSA #7 Limited Partnership"},
		{Code: "080", Network: "Pine Cellular Phones Inc."},
		{Code: "090", Network: "Long Lines Wireless LLC"},
		{Code: "100", Network: "Nex-Tech Wireless LLC"},
		{Code: "120", Network: "Choice Phone LLC"},
		{Code: "130", Network: "Alltel Corp."},
		{Code: "150", Network: "Wilkes Cellular Inc."},
		{Code: "170", Network: "PetroCom"},
		{Code: "190", Network: "Cellular Properties Inc."},
		{Code: "210", Network: "Emery Telcom - Wireless Inc."},
		{Code: "240", Network: "Cordova Wireless Communications Inc."},
		{Code: "250", Network: "Wave Runner LLC"},
		{Code: "260", Network: "SLO Cellular Inc (DBA - Cellular One of San Luis Obispo) and Entertainment Ltd."},
		{Code: "300", Network: "Nexus Communications Inc."},
		{Code: "310", Network: "Lamar County Cellular"},
		{Code: "311", Network: "Farmers"},
		{Code: "330", Network: "Michigan Wireless LLC"},
		{Code: "340", Network: "Illinois Valley Cellular RSA 2 Partnership"},
		{Code: "350", Network: "Sagebrush Cellular Inc."},
		{Code: "370", Network: "GCI Communication Corp."},
		{Code: "380", Network: "New Dimension Wireless Ltd."},
		{Code: "410", Network: "Iowa RSA No. 2 Limited Partnership"},
		{Code: "420", Network: "Northwest Missouri Cellular Limited Partnership"},
		{Code: "430", Network: "RSA 1 Limited Partnership"},
		{Code: "440", Network: "Bluegrass Wireless LLC"},
		{Code: "460", Network: "Fisher Wireless Services Inc."},
		{Code: "500", Network: "Cambridge Telephone Company Inc."},
		{Code: "520", Network: "Crossroads Wireless Inc."},
		{Code: "590", Network: "California RSA No. 3 Limited Partnership"},
		{Code: "610", Network: "North Dakota Network Company"},
		{Code: "650", Network: "United Wireless Communications Inc."},
		{Code: "660", Network: "MetroPCS Communications Inc."},
		{Code: "670", Network: "Pine Belt Cellular, Inc."},
		{Code: "710", Network: "Northeast Wireless Networks LLC"},
		{Code: "730", Network: "Proximity Mobility LLC"},
		{Code: "740", Network: "TelAlaska Cellular Inc."},
		{Code: "910", Network: "SI Wireless LLC"},
	},
}
