package countries

import "github.com/rojack96/mcc/models"

var India404 = models.Mcc{
	Code:        404,
	Iso:         "IN",
	Country:     "India",
	CountryCode: 91,
	Mnc: []models.Mnc{
		{Code: "01", Network: "Aircel Digilink India Ltd."},
		{Code: "04", Network: "Idea Cellular Ltd."},
		{Code: "045", Network: "Bharti Airtel Limited"},
		{Code: "05", Network: "Fascel Ltd."},
		{Code: "07", Network: "Idea Cellular Ltd."},
		{Code: "09", Network: "Reliance Telecom Private Ltd."},
		{Code: "10", Network: "Bharti Airtel Limited"},
		{Code: "11", Network: "Sterling Cellular Ltd."},
		{Code: "12", Network: "Escotel Mobile Communications Pvt Ltd."},
		{Code: "13", Network: "Barakhamba Sales & Services Ltd./Hutchison Essar Limited"},
		{Code: "14", Network: "Spice"},
		{Code: "15", Network: "Aircel Digilink India Ltd."},
		{Code: "16", Network: "Hexcom India"},
		{Code: "17", Network: "Aircel"},
		{Code: "18", Network: "Reliance Telecom Private Ltd."},
		{Code: "19", Network: "Escotel Mobile Communications Pvt Ltd."},
		{Code: "22", Network: "Idea Cellular Ltd."},
		{Code: "24", Network: "Idea Cellular Ltd."},
		{Code: "25", Network: "Aircel"},
		{Code: "28", Network: "Aircel"},
		{Code: "29", Network: "Aircel"},
		{Code: "30", Network: "Usha Martin Telecom Ltd."},
		{Code: "33", Network: "Aircel"},
		{Code: "34", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "36", Network: "Reliance Telecom Private Ltd."},
		{Code: "38", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "41", Network: "RPG Cellular"},
		{Code: "42", Network: "Aircel"},
		{Code: "43", Network: "Vodafone/Essar/Hutch"},
		{Code: "44", Network: "Spice"},
		{Code: "50", Network: "Reliance Telecom Private Ltd."},
		{Code: "51", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "52", Network: "Reliance Telecom Private Ltd."},
		{Code: "53", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "54", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "55", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "56", Network: "Escotel Mobile Communications Pvt Ltd."},
		{Code: "57", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "58", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "59", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "60", Network: "Aircel Digilink India Ltd."},
		{Code: "62", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "64", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "66", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "67", Network: "Reliance Telecom Private Ltd."},
		{Code: "68", Network: "Mahanagar Telephone Nigam Ltd."},
		{Code: "69", Network: "Mahanagar Telephone Nigam Ltd."},
		{Code: "70", Network: "Hexacom India Ltd."},
		{Code: "71", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "72", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "73", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "74", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "75", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "76", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "77", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "78", Network: "IDEA Cellular Ltd."},
		{Code: "79", Network: "CellOne A&N"},
		{Code: "80", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "81", Network: "Bharat Sanchar Nigam Ltd."},
		{Code: "82", Network: "Escorts Telecom Ltd."},
		{Code: "83", Network: "Reliable Internet Services Ltd."},
		{Code: "85", Network: "Reliance Telecom Private Ltd."},
		{Code: "86", Network: "Barakhamba Sales & Services Ltd."},
		{Code: "87", Network: "Escorts Telecom Ltd."},
		{Code: "88", Network: "Escorts Telecom Ltd."},
		{Code: "89", Network: "Escorts Telecom Ltd."},
		{Code: "999", Network: "Various Networks"},
	},
}
