package countries

import "github.com/rojack96/mcc/models"

var Japan440 = models.Mcc{
	Code:        440,
	Iso:         "JP",
	Country:     "Japan",
	CountryCode: 81,
	Mnc: []models.Mnc{
		{Code: "00", Network: "eMobile"},
		{Code: "01", Network: "NTT Docomo"},
		{Code: "02", Network: "NTT Docomo"},
		{Code: "03", Network: "NTT Docomo"},
		{Code: "04", Network: "SoftBank Mobile Corp"},
		{Code: "06", Network: "SoftBank Mobile Corp"},
		{Code: "07", Network: "KDDI Corporation"},
		{Code: "08", Network: "KDDI Corporation"},
		{Code: "09", Network: "NTT Docomo"},
		{Code: "10", Network: "NTT Docomo"},
		{Code: "11", Network: "NTT Docomo"},
		{Code: "12", Network: "NTT Docomo"},
		{Code: "13", Network: "NTT Docomo"},
		{Code: "14", Network: "NTT Docomo"},
		{Code: "15", Network: "NTT Docomo"},
		{Code: "16", Network: "NTT Docomo"},
		{Code: "17", Network: "NTT Docomo"},
		{Code: "18", Network: "NTT Docomo"},
		{Code: "19", Network: "NTT Docomo"},
		{Code: "20", Network: "SoftBank Mobile Corp"},
		{Code: "21", Network: "NTT Docomo"},
		{Code: "22", Network: "NTT Docomo"},
		{Code: "23", Network: "NTT Docomo"},
		{Code: "24", Network: "NTT Docomo"},
		{Code: "25", Network: "NTT Docomo"},
		{Code: "26", Network: "NTT Docomo"},
		{Code: "27", Network: "NTT Docomo"},
		{Code: "28", Network: "NTT Docomo"},
		{Code: "29", Network: "NTT Docomo"},
		{Code: "30", Network: "NTT Docomo"},
		{Code: "31", Network: "NTT Docomo"},
		{Code: "32", Network: "NTT Docomo"},
		{Code: "33", Network: "NTT Docomo"},
		{Code: "34", Network: "NTT Docomo"},
		{Code: "35", Network: "NTT Docomo"},
		{Code: "36", Network: "NTT Docomo"},
		{Code: "37", Network: "NTT Docomo"},
		{Code: "38", Network: "NTT Docomo"},
		{Code: "39", Network: "NTT Docomo"},
		{Code: "40", Network: "SoftBank Mobile Corp"},
		{Code: "41", Network: "SoftBank Mobile Corp"},
		{Code: "42", Network: "SoftBank Mobile Corp"},
		{Code: "43", Network: "SoftBank Mobile Corp"},
		{Code: "44", Network: "SoftBank Mobile Corp"},
		{Code: "45", Network: "SoftBank Mobile Corp"},
		{Code: "46", Network: "SoftBank Mobile Corp"},
		{Code: "47", Network: "SoftBank Mobile Corp"},
		{Code: "48", Network: "SoftBank Mobile Corp"},
		{Code: "49", Network: "NTT Docomo"},
		{Code: "50", Network: "KDDI Corporation"},
		{Code: "51", Network: "KDDI Corporation"},
		{Code: "52", Network: "KDDI Corporation"},
		{Code: "53", Network: "KDDI Corporation"},
		{Code: "54", Network: "KDDI Corporation"},
		{Code: "55", Network: "KDDI Corporation"},
		{Code: "56", Network: "KDDI Corporation"},
		{Code: "58", Network: "NTT Docomo"},
		{Code: "60", Network: "NTT Docomo"},
		{Code: "61", Network: "NTT Docomo"},
		{Code: "62", Network: "NTT Docomo"},
		{Code: "63", Network: "NTT Docomo"},
		{Code: "64", Network: "NTT Docomo"},
		{Code: "65", Network: "NTT Docomo"},
		{Code: "66", Network: "NTT Docomo"},
		{Code: "67", Network: "NTT Docomo"},
		{Code: "68", Network: "NTT Docomo"},
		{Code: "69", Network: "NTT Docomo"},
		{Code: "70", Network: "KDDI Corporation"},
		{Code: "71", Network: "KDDI Corporation"},
		{Code: "72", Network: "KDDI Corporation"},
		{Code: "73", Network: "KDDI Corporation"},
		{Code: "74", Network: "KDDI Corporation"},
		{Code: "75", Network: "KDDI Corporation"},
		{Code: "76", Network: "KDDI Corporation"},
		{Code: "77", Network: "KDDI Corporation"},
		{Code: "79", Network: "KDDI Corporation"},
		{Code: "87", Network: "NTT Docomo"},
		{Code: "88", Network: "KDDI Corporation"},
		{Code: "89", Network: "KDDI Corporation"},
		{Code: "90", Network: "SoftBank Mobile Corp"},
		{Code: "92", Network: "SoftBank Mobile Corp"},
		{Code: "93", Network: "SoftBank Mobile Corp"},
		{Code: "94", Network: "SoftBank Mobile Corp"},
		{Code: "95", Network: "SoftBank Mobile Corp"},
		{Code: "96", Network: "SoftBank Mobile Corp"},
		{Code: "97", Network: "SoftBank Mobile Corp"},
		{Code: "98", Network: "SoftBank Mobile Corp"},
		{Code: "99", Network: "NTT DoCoMo Inc."},
	},
}
