package countries

import "github.com/rojack96/mcc/models"

var Poland = models.Mcc{
	Code:        260,
	Iso:         "PL",
	Country:     "Poland",
	CountryCode: 48,
	Mnc: []models.Mnc{
		{Code: "299", Network: "3S"},
		{Code: "17", Network: "Aero2"},
		{Code: "16", Network: "Aero2"},
		{Code: "15", Network: "Aero2"},
		{Code: "04", Network: "Aero2"},
		{Code: "48", Network: "Agile Telecom"},
		{Code: "18", Network: "AMD Telecom"},
		{Code: "299", Network: "Benemen"},
		{Code: "299", Network: "BSG"},
		{Code: "299", Network: "Caritas Laczy"},
		{Code: "299", Network: "Cludo"},
		{Code: "32", Network: "Compatel"},
		{Code: "12", Network: "Cyfrowy Polsat"},
		{Code: "299", Network: "e-Telko"},
		{Code: "41", Network: "EZ Mobile"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "299", Network: "I.M. Consulting"},
		{Code: "299", Network: "Inea"},
		{Code: "299", Network: "IZZI"},
		{Code: "299", Network: "JMDI J. Maleszko"},
		{Code: "299", Network: "Klucz Mobile"},
		{Code: "299", Network: "lajt mobile"},
		{Code: "299", Network: "LoVo"},
		{Code: "09", Network: "Lycamobile"},
		{Code: "49", Network: "Messagebird"},
		{Code: "299", Network: "Metro Mobile"},
		{Code: "299", Network: "Mobile Vikings"},
		{Code: "299", Network: "Mobiledata"},
		{Code: "42", Network: "MobiWeb"},
		{Code: "299", Network: "Moja GSM"},
		{Code: "13", Network: "Move"},
		{Code: "299", Network: "multiMOBILE"},
		{Code: "299", Network: "Nasza Wizja"},
		{Code: "299", Network: "NAU Mobile"},
		{Code: "299", Network: "nc+ Mobile"},
		{Code: "19", Network: "NetBalt"},
		{Code: "07", Network: "Netia"},
		{Code: "299", Network: "Next Mobile"},
		{Code: "299", Network: "NIMBOW"},
		{Code: "27", Network: "Ntel Solutions"},
		{Code: "05", Network: "Orange"},
		{Code: "03", Network: "Orange"},
		{Code: "35", Network: "PKP"},
		{Code: "98", Network: "Play"},
		{Code: "06", Network: "Play"},
		{Code: "11", Network: "Plus"},
		{Code: "01", Network: "Plus"},
		{Code: "97", Network: "Politechnika Lodzka Uczelniane"},
		{Code: "90", Network: "Polska Spolka Gazownictwa"},
		{Code: "299", Network: "Polvoice"},
		{Code: "299", Network: "Pomagacz"},
		{Code: "299", Network: "Premium Mobile"},
		{Code: "299", Network: "Premium Numbers"},
		{Code: "299", Network: "SAT FILM"},
		{Code: "14", Network: "Move"},
		{Code: "299", Network: "SGT"},
		{Code: "47", Network: "SMSHIGHWAY"},
		{Code: "299", Network: "Softelnet"},
		{Code: "34", Network: "T-Mobile"},
		{Code: "02", Network: "T-Mobile"},
		{Code: "10", Network: "T-Mobile"},
		{Code: "14", Network: "Telco Leaders"},
		{Code: "299", Network: "Tele GO"},
		{Code: "299", Network: "TeleCube"},
		{Code: "299", Network: "Telenabler"},
		{Code: "299", Network: "TELGAM"},
		{Code: "20", Network: "Tismi"},
		{Code: "299", Network: "TOYAmobilna"},
		{Code: "22", Network: "Twilio"},
		{Code: "299", Network: "UPC"},
		{Code: "299", Network: "Vectra"},
		{Code: "45", Network: "Virgin Mobile"},
		{Code: "299", Network: "Vonage"},
		{Code: "39", Network: "Voxbone / Bandwidth"},
		{Code: "299", Network: "w naszej Rodzinie"},
	},
}
