package countries

import "github.com/rojack96/mcc/models"

var UnitedKingdom = models.Mcc{
	Code:        234,
	Iso:         "GB",
	Country:     "United Kingdom",
	CountryCode: 44,
	Mnc: []models.Mnc{
		{Code: "78", Network: "Airwave"},
		{Code: "29", Network: "aql"},
		{Code: "76", Network: "BT Group"},
		{Code: "00", Network: "BT Group"},
		{Code: "08", Network: "BT OnePhone"},
		{Code: "18", Network: "Cloud9"},
		{Code: "30", Network: "EE/Everything Everywhere"},
		{Code: "32", Network: "EE/Everything Everywhere"},
		{Code: "33", Network: "EE/Everything Everywhere"},
		{Code: "31", Network: "EE/Everything Everywhere"},
		{Code: "299", Network: "Failed Calls"},
		{Code: "999", Network: "Fix Line"},
		{Code: "17", Network: "FlexTel"},
		{Code: "04", Network: "FMS Solutions"},
		{Code: "39", Network: "Gamma Mobile"},
		{Code: "24", Network: "Greenfone"},
		{Code: "72", Network: "Hanhaa Mobile"},
		{Code: "71", Network: "Home Office"},
		{Code: "20", Network: "3"},
		{Code: "94", Network: "3"},
		{Code: "23", Network: "Icron Network"},
		{Code: "03", Network: "Jersey Airtel"},
		{Code: "35", Network: "JSC Ingenicum"},
		{Code: "50", Network: "JT Mobile"},
		{Code: "14", Network: "LINK Mobility"},
		{Code: "26", Network: "Lycamobile"},
		{Code: "58", Network: "Manx Telecom Mobile"},
		{Code: "28", Network: "Marathon Telecom"},
		{Code: "75", Network: "Mass Response Service GmbH"},
		{Code: "56", Network: "NCSC"},
		{Code: "95", Network: "Network Rail"},
		{Code: "12", Network: "Network Rail"},
		{Code: "13", Network: "Network Rail"},
		{Code: "51", Network: "now broadband"},
		{Code: "34", Network: "Orange"},
		{Code: "74", Network: "Pareteum"},
		{Code: "57", Network: "Sky"},
		{Code: "40", Network: "spusu"},
		{Code: "55", Network: "Sure Guernsey"},
		{Code: "36", Network: "Sure Isle of Man"},
		{Code: "99", Network: "Sure Jersey"},
		{Code: "37", Network: "Synectiv"},
		{Code: "16", Network: "Talk Talk"},
		{Code: "27", Network: "Tata Communications Ltd"},
		{Code: "11", Network: "O2"},
		{Code: "10", Network: "O2"},
		{Code: "02", Network: "O2"},
		{Code: "22", Network: "Telesign Mobile"},
		{Code: "19", Network: "TeleWare"},
		{Code: "09", Network: "Tismi"},
		{Code: "25", Network: "Truphone"},
		{Code: "01", Network: "Vectone Mobile"},
		{Code: "38", Network: "Virgin Mobile"},
		{Code: "91", Network: "Vodafone"},
		{Code: "07", Network: "Vodafone"},
		{Code: "15", Network: "Vodafone"},
		{Code: "92", Network: "Vodafone"},
		{Code: "77", Network: "Vodafone"},
		{Code: "89", Network: "Vodafone"},
	},
}
